package ecomoter.myapplication.model;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import ecomoter.myapplication.model.User;
import ecomoter.myapplication.model.Teacher;
import ecomoter.myapplication.model.NewTable;
import ecomoter.myapplication.mvpbase.Student;

import ecomoter.myapplication.model.UserDao;
import ecomoter.myapplication.model.TeacherDao;
import ecomoter.myapplication.model.NewTableDao;
import ecomoter.myapplication.mvpbase.StudentDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig teacherDaoConfig;
    private final DaoConfig newTableDaoConfig;
    private final DaoConfig studentDaoConfig;

    private final UserDao userDao;
    private final TeacherDao teacherDao;
    private final NewTableDao newTableDao;
    private final StudentDao studentDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        teacherDaoConfig = daoConfigMap.get(TeacherDao.class).clone();
        teacherDaoConfig.initIdentityScope(type);

        newTableDaoConfig = daoConfigMap.get(NewTableDao.class).clone();
        newTableDaoConfig.initIdentityScope(type);

        studentDaoConfig = daoConfigMap.get(StudentDao.class).clone();
        studentDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        teacherDao = new TeacherDao(teacherDaoConfig, this);
        newTableDao = new NewTableDao(newTableDaoConfig, this);
        studentDao = new StudentDao(studentDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Teacher.class, teacherDao);
        registerDao(NewTable.class, newTableDao);
        registerDao(Student.class, studentDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        teacherDaoConfig.clearIdentityScope();
        newTableDaoConfig.clearIdentityScope();
        studentDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public TeacherDao getTeacherDao() {
        return teacherDao;
    }

    public NewTableDao getNewTableDao() {
        return newTableDao;
    }

    public StudentDao getStudentDao() {
        return studentDao;
    }

}
